# Generated by Django 3.1.2 on 2020-10-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=15)),
                ('area_code', models.IntegerField()),
                ('number', models.IntegerField()),
                ('contact_id', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=25)),
                ('date', models.DateField()),
                ('contact_id', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'Date',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip', models.IntegerField()),
                ('contact_id', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
            ],
            options={
                'db_table': 'Address',
            },
        ),
    ]
