# Generated by Django 3.1.2 on 2020-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201008_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
